# Generated by Django 2.0.6 on 2018-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('technogies_used', models.CharField(max_length=255)),
                ('github_link', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
