# Generated by Django 2.0.6 on 2018-06-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180605_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Portfolio_Project',
        ),
    ]
