# Generated by Django 2.0.6 on 2018-06-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180605_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio_Project',
            new_name='PortfolioProject',
        ),
    ]
