# Generated by Django 2.0.6 on 2018-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180605_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='project_description',
            field=models.TextField(),
        ),
    ]
