# Generated by Django 2.0.6 on 2018-06-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180606_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioproject',
            old_name='technogies_used',
            new_name='technoligies_used',
        ),
    ]
